[package]
name = "turf_api_monolith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
redis = "0.23.0"
tokio = "1.29.1"
